-- 코드를 입력하세요
-- AGE < 12
-- GEND_CD = 'W'
-- NVL(TLNO, 'NONE')
-- ORDER BY AGE DESC, PT_NAME ASC;


SELECT PT_NAME, PT_NO, GEND_CD, AGE, NVL(TLNO, 'NONE')
FROM PATIENT
WHERE GEND_CD = 'W'
AND AGE <= 12
ORDER BY AGE DESC, PT_NAME ASC;
